baseURL = "https://llxyo.github.io/"
languageCode = "ja"
title = "LLxyo-Blog"
author = "LLxyo"
paginate = 10
favicon = "/static/favicon.ico"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:filename/"

[imaging]
  quality =  99

[params]
  description =  "<b>I'm LLxyo.</b><br><b>I mainly blog about comics, anime, and so on.</b>"
  katex =  true

[menu]
   [[menu.nav]]
     name =  "Blog"
     url=  "/post/"
     weight =  1
   [[menu.nav]]
     name =  "Tags"
     url =  "/tags/"
     weight =  2
[markup]
  defaultMarkdownHandler = "blackfriday"

[blackfriday]
  hrefTargetBlank = true