baseURL = "https://llxyo.github.io/"
languageCode = "ja"
title = "LLxyo's Daydreams"
author = "LLxyo"
paginate = 10
contentdir = "content"
layoutdir = "layouts"
favicon = "/static/favicon.ico"
publishDir = "docs"
googleAnalytics = "UA-110948318-1"
archive = "archives"
hasCJKLanguage = true
summaryLength = 60

[taxonomies]
  category = "categories"
  series = "series"
  brand = "brand"
  genre = "genre"

[permalinks]
  post = "/post/:filename/"

[imaging]
  quality =  99

[params]
  title = "LLxyo's Daydreams"
  description =  "<b>I'm LLxyo.</b><br><b>I mainly blog about anime, comics and light novels like that.</b>"
  katex =  true
  images = ["Card.png"]

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]] # relatedに関連付ける要素とその度合いを指定
    name = "series"
    weight = 100
  
  [[related.indices]]
    name = "genre"
    weight = 80

  [[related.indices]]
    name = "brand"
    weight = 80
  
  [[related.indices]]
    name = "categories"
    weight = 50

[menu]
   [[menu.nav]]
     name =  "Posts"
     url=  "/post/"
     weight =  1
[[menu.nav]]
     name =  "Categories"
     url =  "/categories/"
     weight =  2
   [[menu.nav]] # taxonomies一覧にリンク
     name =  "Tags"
     url =  "/taxonomies/"
     weight =  3
   [[menu.nav]]
     name = "About"
     url = "/about/"
     weight = 4
   [[menu.nav]]
     name = "RSS"
     url = "/index.xml"
     weight = 5
   [[menu.nav]]
     name = "in Farsi"
     url = "/fa/"
     weight = 6

[markup]
  defaultMarkdownHandler = "blackfriday"

[markup.goldmark]
[markup.goldmark.renderer]
      unsafe = true

[blackfriday]
  hrefTargetBlank = true