baseURL = "https://llxyo.github.io/"
languageCode = "ja"
title = "LLxyo-Blog"
author = "LLxyo"
paginate = 10
contentdir = "content"
layoutdir = "layouts"
favicon = "/static/favicon.ico"
publishDir = "docs"
googleAnalytics = "UA-110948318-1"
archive = "archives"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/post/:filename/"

[imaging]
  quality =  99

[params]
  description =  "<b>I'm LLxyo.</b><br><b>I mainly blog about comics, anime, and so on.</b>"
  katex =  true
  images = "favicon-96x96.png"

[menu]
   [[menu.nav]]
     name =  "Blog"
     url=  "/post/"
     weight =  1
[[menu.nav]]
     name =  "Categories"
     url =  "/categories/"
     weight =  2
   [[menu.nav]]
     name =  "Tags"
     url =  "/tags/"
     weight =  3
   [[menu.nav]]
     name = "About"
     url = "/about/"
     weight = 4
   [[menu.nav]]
     name = "RSS"
     url = "/index.xml"
     weight = 5
   [[menu.nav]]
     name = "in Farsi"
     url = "/fa/"
     weight = 6

[markup]
  defaultMarkdownHandler = "blackfriday"

[blackfriday]
  hrefTargetBlank = true